// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/neo4j/cli/common/analytics (interfaces: Service,HTTPClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_analytics.go -package=analytics_mocks -typed github.com/neo4j/cli/common/analytics Service,HTTPClient
//

// Package analytics_mocks is a generated GoMock package.
package analytics_mocks

import (
	io "io"
	http "net/http"
	reflect "reflect"

	analytics "github.com/neo4j/cli/common/analytics"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Disable mocks base method.
func (m *MockService) Disable() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Disable")
}

// Disable indicates an expected call of Disable.
func (mr *MockServiceMockRecorder) Disable() *MockServiceDisableCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable", reflect.TypeOf((*MockService)(nil).Disable))
	return &MockServiceDisableCall{Call: call}
}

// MockServiceDisableCall wrap *gomock.Call
type MockServiceDisableCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceDisableCall) Return() *MockServiceDisableCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceDisableCall) Do(f func()) *MockServiceDisableCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceDisableCall) DoAndReturn(f func()) *MockServiceDisableCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EmitCommandEvent mocks base method.
func (m *MockService) EmitCommandEvent(command string, success bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EmitCommandEvent", command, success)
}

// EmitCommandEvent indicates an expected call of EmitCommandEvent.
func (mr *MockServiceMockRecorder) EmitCommandEvent(command, success any) *MockServiceEmitCommandEventCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitCommandEvent", reflect.TypeOf((*MockService)(nil).EmitCommandEvent), command, success)
	return &MockServiceEmitCommandEventCall{Call: call}
}

// MockServiceEmitCommandEventCall wrap *gomock.Call
type MockServiceEmitCommandEventCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceEmitCommandEventCall) Return() *MockServiceEmitCommandEventCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceEmitCommandEventCall) Do(f func(string, bool)) *MockServiceEmitCommandEventCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceEmitCommandEventCall) DoAndReturn(f func(string, bool)) *MockServiceEmitCommandEventCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EmitEvent mocks base method.
func (m *MockService) EmitEvent(event analytics.TrackEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EmitEvent", event)
}

// EmitEvent indicates an expected call of EmitEvent.
func (mr *MockServiceMockRecorder) EmitEvent(event any) *MockServiceEmitEventCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitEvent", reflect.TypeOf((*MockService)(nil).EmitEvent), event)
	return &MockServiceEmitEventCall{Call: call}
}

// MockServiceEmitEventCall wrap *gomock.Call
type MockServiceEmitEventCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceEmitEventCall) Return() *MockServiceEmitEventCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceEmitEventCall) Do(f func(analytics.TrackEvent)) *MockServiceEmitEventCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceEmitEventCall) DoAndReturn(f func(analytics.TrackEvent)) *MockServiceEmitEventCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EmitStartupEvent mocks base method.
func (m *MockService) EmitStartupEvent() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EmitStartupEvent")
}

// EmitStartupEvent indicates an expected call of EmitStartupEvent.
func (mr *MockServiceMockRecorder) EmitStartupEvent() *MockServiceEmitStartupEventCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitStartupEvent", reflect.TypeOf((*MockService)(nil).EmitStartupEvent))
	return &MockServiceEmitStartupEventCall{Call: call}
}

// MockServiceEmitStartupEventCall wrap *gomock.Call
type MockServiceEmitStartupEventCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceEmitStartupEventCall) Return() *MockServiceEmitStartupEventCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceEmitStartupEventCall) Do(f func()) *MockServiceEmitStartupEventCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceEmitStartupEventCall) DoAndReturn(f func()) *MockServiceEmitStartupEventCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Enable mocks base method.
func (m *MockService) Enable() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Enable")
}

// Enable indicates an expected call of Enable.
func (mr *MockServiceMockRecorder) Enable() *MockServiceEnableCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enable", reflect.TypeOf((*MockService)(nil).Enable))
	return &MockServiceEnableCall{Call: call}
}

// MockServiceEnableCall wrap *gomock.Call
type MockServiceEnableCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceEnableCall) Return() *MockServiceEnableCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceEnableCall) Do(f func()) *MockServiceEnableCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceEnableCall) DoAndReturn(f func()) *MockServiceEnableCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Flush mocks base method.
func (m *MockService) Flush() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Flush")
}

// Flush indicates an expected call of Flush.
func (mr *MockServiceMockRecorder) Flush() *MockServiceFlushCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockService)(nil).Flush))
	return &MockServiceFlushCall{Call: call}
}

// MockServiceFlushCall wrap *gomock.Call
type MockServiceFlushCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceFlushCall) Return() *MockServiceFlushCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceFlushCall) Do(f func()) *MockServiceFlushCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceFlushCall) DoAndReturn(f func()) *MockServiceFlushCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsEnabled mocks base method.
func (m *MockService) IsEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEnabled indicates an expected call of IsEnabled.
func (mr *MockServiceMockRecorder) IsEnabled() *MockServiceIsEnabledCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEnabled", reflect.TypeOf((*MockService)(nil).IsEnabled))
	return &MockServiceIsEnabledCall{Call: call}
}

// MockServiceIsEnabledCall wrap *gomock.Call
type MockServiceIsEnabledCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceIsEnabledCall) Return(arg0 bool) *MockServiceIsEnabledCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceIsEnabledCall) Do(f func() bool) *MockServiceIsEnabledCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceIsEnabledCall) DoAndReturn(f func() bool) *MockServiceIsEnabledCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockHTTPClient is a mock of HTTPClient interface.
type MockHTTPClient struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPClientMockRecorder
	isgomock struct{}
}

// MockHTTPClientMockRecorder is the mock recorder for MockHTTPClient.
type MockHTTPClientMockRecorder struct {
	mock *MockHTTPClient
}

// NewMockHTTPClient creates a new mock instance.
func NewMockHTTPClient(ctrl *gomock.Controller) *MockHTTPClient {
	mock := &MockHTTPClient{ctrl: ctrl}
	mock.recorder = &MockHTTPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPClient) EXPECT() *MockHTTPClientMockRecorder {
	return m.recorder
}

// Post mocks base method.
func (m *MockHTTPClient) Post(url, contentType string, body io.Reader) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", url, contentType, body)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Post indicates an expected call of Post.
func (mr *MockHTTPClientMockRecorder) Post(url, contentType, body any) *MockHTTPClientPostCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockHTTPClient)(nil).Post), url, contentType, body)
	return &MockHTTPClientPostCall{Call: call}
}

// MockHTTPClientPostCall wrap *gomock.Call
type MockHTTPClientPostCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHTTPClientPostCall) Return(arg0 *http.Response, arg1 error) *MockHTTPClientPostCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHTTPClientPostCall) Do(f func(string, string, io.Reader) (*http.Response, error)) *MockHTTPClientPostCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHTTPClientPostCall) DoAndReturn(f func(string, string, io.Reader) (*http.Response, error)) *MockHTTPClientPostCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
