name: License

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

permissions:
    contents: read

jobs:
    license-header-check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
            - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
              with:
                  go-version: "1.26.5"
            - name: Install addlicense
              run: go install github.com/google/addlicense@latest
            - name: Run addlicense
              run: addlicense -f ./addlicense -check $(find . -name "*.go" -type f -print0 | xargs -0)
